### ISSUE TITLE
[huggingface executor] RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by ifTNT** [kuwaai/genai-os#20]
## Version
- Kuwa GenAI OS: 0.3.1
- PyTorch: 2.3.1
- CUDA: 12.5

## Expected Behavior
The `--visible_gpu` argument of the HuggingFace executor should restrict the GPU used for execution.

## Actual Behavior
The executor crashed when loading model
```
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 306, in _lazy_init
    queued_call()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 174, in _check_capability
    capability = get_device_capability(d)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 448, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=
```

**Comment by ifTNT** [comment]
**Resolution:**

- Relevant issue: https://github.com/pytorch/pytorch/issues/128819
- **Impact:** Affects PyTorch versions greater than 2.2.1 (including 2.3.0 and 2.3.1)
- **Mitigation:** Upgrade to PyTorch 2.4.0 using the following command:

```
pip3 install --upgrade --force-reinstall torch==2.4.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu124
```

**Comment by vananh0905** [comment]
Hi @ifTNT,
I installed pytorch 2.4.0 but still face the same issue.

<img width="726" alt="Image" src="https://github.com/user-attachments/assets/aab8f708-3472-4180-b8a6-157878b58788" />
